import type { Product } from '~/types/Product';

const averageRating = { rate: 4.5, count: 200 };

export const mockProducts: Product[] = [
	{
		id: 1,
		name: 'Notebook Gamer',
		price: 4699.99,
		description: 'Notebook de alta performance para jogos e trabalho',
		category: 'Eletrônicos',
		inStock: true,
		image: 'https://m.media-amazon.com/images/I/71boK7lWqmL._AC_SY450_.jpg',
		rating: averageRating,
	},
	{
		id: 2,
		name: 'Mouse Ergonômico',
		price: 89.9,
		description: 'Mouse com design ergonômico e precisão óptica',
		category: 'Periféricos',
		inStock: true,
		image: 'https://m.media-amazon.com/images/I/61OkuiCWbDL._AC_SY300_SX300_QL70_ML2_.jpg',
		rating: averageRating,
	},
	{
		id: 3,
		name: 'Teclado Mecânico',
		price: 349.99,
		description: 'Teclado mecânico RGB com switches blue',
		category: 'Periféricos',
		inStock: false,
		image: 'https://m.media-amazon.com/images/I/61qYXdRL7OL._AC_SX679_.jpg',
		rating: { rate: 4.1, count: 50 },
	},
	{
		id: 4,
		name: 'Monitor 27"',
		price: 1299.0,
		description: 'Monitor LED Full HD 27 polegadas',
		category: 'Eletrônicos',
		inStock: true,
		image: 'https://m.media-amazon.com/images/I/71NHsNfW4tL._AC_SX679_.jpg',
		rating: averageRating,
	},
	{
		id: 5,
		name: 'Webcam HD',
		price: 279.9,
		description: 'Webcam 1080p com microfone embutido',
		category: 'Periféricos',
		inStock: true,
		image: 'https://m.media-amazon.com/images/I/61SCZyiMSNL._AC_SY300_SX300_QL70_ML2_.jpg',
		rating: averageRating,
	},
	{
		id: 6,
		name: 'Headset Gamer',
		price: 199.99,
		description: 'Headset com som surround 7.1 e LED RGB',
		category: 'Áudio',
		inStock: false,
		image: 'https://m.media-amazon.com/images/I/71RSZdY7pJL._AC_SY300_SX300_QL70_ML2_.jpg',
		rating: { rate: 5, count: 10 },
	},
];
